# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

parameters:
- name: Login
  displayName: User login (e.g. jsmith)
  type: string
  default: ''
- name: Name
  displayName: User name (e.g. John Smith)
  type: string
  default: ''
- name: Email
  displayName: Email (@opengi.co.uk, @opengi.pl or @opengi.mk)
  type: string
  default: ''
- name: TenantSource
  displayName: Tenant source
  type: string
  default: 'n/a'
  values:
  - n/a
  - integration
  - prod
- name: SiteCode
  displayName: Tenant sitecode
  type: string
  default: 'VM00'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
